require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TextualPagesController do

  # This should return the minimal set of attributes required to create a valid
  # TextualPage. As you add validations to TextualPage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all textual_pages as @textual_pages" do
      textual_page = TextualPage.create! valid_attributes
      get :index
      assigns(:textual_pages).should eq([textual_page])
    end
  end

  describe "GET show" do
    it "assigns the requested textual_page as @textual_page" do
      textual_page = TextualPage.create! valid_attributes
      get :show, :id => textual_page.id.to_s
      assigns(:textual_page).should eq(textual_page)
    end
  end

  describe "GET new" do
    it "assigns a new textual_page as @textual_page" do
      get :new
      assigns(:textual_page).should be_a_new(TextualPage)
    end
  end

  describe "GET edit" do
    it "assigns the requested textual_page as @textual_page" do
      textual_page = TextualPage.create! valid_attributes
      get :edit, :id => textual_page.id.to_s
      assigns(:textual_page).should eq(textual_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TextualPage" do
        expect {
          post :create, :textual_page => valid_attributes
        }.to change(TextualPage, :count).by(1)
      end

      it "assigns a newly created textual_page as @textual_page" do
        post :create, :textual_page => valid_attributes
        assigns(:textual_page).should be_a(TextualPage)
        assigns(:textual_page).should be_persisted
      end

      it "redirects to the created textual_page" do
        post :create, :textual_page => valid_attributes
        response.should redirect_to(TextualPage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved textual_page as @textual_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        TextualPage.any_instance.stub(:save).and_return(false)
        post :create, :textual_page => {}
        assigns(:textual_page).should be_a_new(TextualPage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TextualPage.any_instance.stub(:save).and_return(false)
        post :create, :textual_page => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested textual_page" do
        textual_page = TextualPage.create! valid_attributes
        # Assuming there are no other textual_pages in the database, this
        # specifies that the TextualPage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TextualPage.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => textual_page.id, :textual_page => {'these' => 'params'}
      end

      it "assigns the requested textual_page as @textual_page" do
        textual_page = TextualPage.create! valid_attributes
        put :update, :id => textual_page.id, :textual_page => valid_attributes
        assigns(:textual_page).should eq(textual_page)
      end

      it "redirects to the textual_page" do
        textual_page = TextualPage.create! valid_attributes
        put :update, :id => textual_page.id, :textual_page => valid_attributes
        response.should redirect_to(textual_page)
      end
    end

    describe "with invalid params" do
      it "assigns the textual_page as @textual_page" do
        textual_page = TextualPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TextualPage.any_instance.stub(:save).and_return(false)
        put :update, :id => textual_page.id.to_s, :textual_page => {}
        assigns(:textual_page).should eq(textual_page)
      end

      it "re-renders the 'edit' template" do
        textual_page = TextualPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TextualPage.any_instance.stub(:save).and_return(false)
        put :update, :id => textual_page.id.to_s, :textual_page => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested textual_page" do
      textual_page = TextualPage.create! valid_attributes
      expect {
        delete :destroy, :id => textual_page.id.to_s
      }.to change(TextualPage, :count).by(-1)
    end

    it "redirects to the textual_pages list" do
      textual_page = TextualPage.create! valid_attributes
      delete :destroy, :id => textual_page.id.to_s
      response.should redirect_to(textual_pages_url)
    end
  end

end
